# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MediaPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MediaPlayer
  pod 'Kanna', :git => 'https://github.com/tid-kijyun/Kanna.git', :branch => 'feature/v4.0.0'
  pod 'TGPControls'
end
